services:
  proxy:
    image: nginx
    container_name: proxy
    ports:
      - "80:80"
      - "81:81"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - was-application
      - web-application

  was-application:
    build: .
    image: inewpow/secondhand
    ports:
      - "8080:8080"
    container_name: was-application
    depends_on:
      - redis
    networks:
      - app-net
      - default

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  web-application:
    image: inewpow/secondhand-web
    container_name: web-application
    ports:
      - "5173:5173"
    depends_on:
      - was-application
    networks:
      - default
      - app-net

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:

networks:
  app-net:
    driver: bridge

                   
