version: "3"

services:
  balancer:
    image: nginx
    container_name: proxy
    ports:
      - "80:80"
      - "81:81"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - was-application
      - web-application

  was-application:
    build: .
    image: inewpow/secondhand
    ports:
      - "8080:8080"
    container_name: was-application
    depends_on:
      - redis
    networks:
      - default

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data/redisdb

  web-application:
    image: inewpow/secondhand-web
    container_name: web-application
    ports:
      - "5173:5173"
    depends_on:
      - was-application
    networks:
      - default

volumes:
  mongodb-data:
