version: "3.7"
services:
  was:
    image: inewpow/secondhand-nginx
    container_name: was-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - application

  application:
    build: .
    image: inewpow/secondhand
    container_name: was-application
    ports:
      - "8080:8080"
    expose:
      - 8080
    depends_on:
      - redis

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
