server:
  address:
    domain: "http://fivehands-but-iiiiii.site"
    was: "3.38.162.177"
chat:
  bubble:
    key: "chatroom::bubble::"
    page-size: 25
  notification:
    time-out: 720000
  meta:
    meta-info-key: "chatroom::meta::"
    connection-key:
