spring:
  profiles:
    active: prod
    group:
      local: [ db-local, local ] # localhost
      prod: [ prod ] # production
      test: [ test ] #test
    include: [ aws, jwt, oauth ]
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 500MB
  jpa:
    properties:
      hibernate:
        jdbc:
        default_batch_fetch_size: 100
    open-in-view: false
server:
  address:
    domain: "http://fivehands-but-iiiiii.site"
    was2: "3.38.162.177"
const:
  chat:
    bucket: "chatroom:"
    page-size: 25
