server:
  servlet:
#    context-path: /api
spring:
  profiles:
    active: prod
    group:
      local: [ local ] # localhost
      prod: [ prod ] # production
      test: [ test ]
    include: [ aws, jwt, oauth, common ]
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 500MB
  jpa:
    properties:
      hibernate:
        jdbc:
        default_batch_fetch_size: 100
    open-in-view: false
