# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'second-hand' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for second-hand
  pod 'SwiftLint' 
  pod 'SwiftStomp'
  pod 'StompClientLib'
end
